CREATE TABLE FUNCIONARIO (
	PRIMEIRO_NOME VARCHAR(30) NOT NULL,
	SEGUNDO_NOME VARCHAR(30),
	ULTIMO_NOME VARCHAR(30) NOT NULL,
	LOGRADOURO_FUNCIONARIO VARCHAR(100),
	NUMERO_FUNCIONARIO INTEGER,
	BAIRRO_FUNCIONARIO VARCHAR(100),
	CIDADE_FUNCIONARIO VARCHAR(100),
	CEP_FUNCIONARIO VARCHAR(8),
	SEXO VARCHAR(1),
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	DATA_NASC DATE,
	NIVEL_CARGO VARCHAR(11),
	CONSTRAINT PK_FUNCIONARIO
	PRIMARY KEY (CPF_FUNCIONARIO)
);

CREATE TABLE TELEFONES_FUNCIONARIO (
	ID_TELEFONE SERIAL NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	CONSTRAINT PK_TELEFONES_FUNCIONARIO PRIMARY KEY (ID_TELEFONE),
	CONSTRAINT FK_FUNC_TEL_FUNC FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO)
);

CREATE TABLE DEPENDENTES (
	CPF_DEPENDENTE VARCHAR(11) NOT NULL,
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	PRIMEIRO_NOME VARCHAR(30) NOT NULL,
	SEGUNDO_NOME VARCHAR(30) NOT NULL,
	ULTIMO_NOME VARCHAR(30) NOT NULL,
	LOGRADOURO_DEPENDENTE VARCHAR(100),
	NUMERO_DEPENDENTE INTEGER,
	BAIRRO_DEPENDENTE VARCHAR(100),
	CIDADE_DEPENDENTE VARCHAR(100),
	CEP_DEPENDENTE VARCHAR(8),
	SEXO VARCHAR(1),
	DATA_NASC DATE,
	CONSTRAINT FK_FUNC_DEPEND FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO),
	CONSTRAINT PK_DEPENDENTES PRIMARY KEY (CPF_DEPENDENTE, CPF_FUNCIONARIO)
);

CREATE TABLE DEPARTAMENTO (
	NUMERO_DEP INTEGER NOT NULL,
	NOME_DEP VARCHAR(50) NOT NULL,
	LOCAL_DEP VARCHAR(100) NOT NULL,
	CPF_GERENTE VARCHAR(11),
	CONSTRAINT FK_GERENTE FOREIGN KEY (CPF_GERENTE) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO),
	CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (NUMERO_DEP)
);

ALTER TABLE FUNCIONARIO
ADD COLUMN NUMERO_DEP INTEGER;

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_DEP_FUNC FOREIGN KEY (NUMERO_DEP) REFERENCES DEPARTAMENTO (NUMERO_DEP);

CREATE TABLE PROJETOS (
	COD_PROJETO INTEGER NOT NULL,
	NOME_PROJETO VARCHAR(30) NOT NULL,
	DATA_PROJETO DATE NOT NULL,
	NUMERO_DEP INTEGER NOT NULL,
	CONSTRAINT FK_DEP_PROJETO FOREIGN KEY (NUMERO_DEP) REFERENCES DEPARTAMENTO (NUMERO_DEP),
	CONSTRAINT PK_PROJETOS PRIMARY KEY (COD_PROJETO)
);

CREATE TABLE PROJETOS_FUNC (
	COD_PROJETO INTEGER NOT NULL,
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	HORAS_PROJETO INTEGER NOT NULL,
	CONSTRAINT FK_FUNC_PROJETOS_FUNC FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIO (CPF_FUNCIONARIO),
	CONSTRAINT FK_PROJETOS_PROJETOS_FUNC FOREIGN KEY (COD_PROJETO) REFERENCES PROJETOS (COD_PROJETO),
	CONSTRAINT PK_PROJETOS_FUNC PRIMARY KEY (COD_PROJETO, CPF_FUNCIONARIO)
);
