CREATE TABLE CARGOS (
	ID_CARGO INT NOT NULL,
	NOME_CARGO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO)
);

CREATE TABLE FUNCIONARIOS (
	CPF VARCHAR(11) NOT NULL,
	NOME_COMPLETO VARCHAR(100) NOT NULL,
	LOGRADOURO VARCHAR(100),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	CEP VARCHAR(8),
	TELEFONE_FIXO VARCHAR(20),
	TELEFONE_CEL VARCHAR(20),
	DATA_NASC DATE,
	ID_CARGO INTEGER NOT NULL,
	CONSTRAINT FK_CARGOS_FUNCIONARIOS FOREIGN KEY (ID_CARGO) REFERENCES CARGOS (ID_CARGO),
	CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (CPF)
);

CREATE TABLE CLIENTES (
	CPF VARCHAR(11) NOT NULL,
	NOME_COMPLETO VARCHAR(100) NOT NULL,
	LOGRADOURO VARCHAR(100),
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	CEP VARCHAR(8),
	TELEFONE_COMERCIAL VARCHAR(20),
	TELEFONE_FIXO VARCHAR(20),
	TELEFONE_CELULAR VARCHAR(20) NOT NULL,
	DATA_NASC DATE,
	EMAIL VARCHAR(200),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (CPF)
);

CREATE TABLE ANIMAL (
	ID_ANIMAL INT NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	DATA_NASC DATE,
	SEXO CHAR(1),
	RACA VARCHAR(30),
	COR VARCHAR(30),
	TIPO VARCHAR(50),
	CONSTRAINT PK_ANIMAL PRIMARY KEY (ID_ANIMAL)
);

CREATE TABLE SERVICOS (
	ID_SERVICO INT NOT NULL,
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	CPF_CLIENTE VARCHAR(11) NOT NULL,
	ID_ANIMAL INT NOT NULL,
	TIPO_SERVICO VARCHAR(100) NOT NULL,
	DATA_SERVICO DATE NOT NULL,
	VALOR_SERVICO NUMERIC (10,2) NOT NULL,
	CONSTRAINT FK_FUNC_SERVICOS FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIOS (CPF),
	CONSTRAINT FK_CLIENTE_SERVICOS FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES (CPF),
	CONSTRAINT FK_ANIMAL_SERVICOS FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL (ID_ANIMAL),
	CONSTRAINT PK_SERVICOS PRIMARY KEY (ID_SERVICO)
);

CREATE TABLE FORNECEDORES (
	ID_FORNECEDOR INT NOT NULL,
	NOME_FORNECEDOR VARCHAR(30) NOT NULL,
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID_FORNECEDOR)
);

CREATE TABLE PRODUTOS (
	ID_PRODUTO INT NOT NULL,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	MARCA VARCHAR(50) NOT NULL,
	VALOR_UNIT NUMERIC(10,2) NOT NULL,
	VALIDADE DATE NOT NULL,
	ID_FORNECEDOR INT NOT NULL,
	CONSTRAINT FK_FORNECEDORES_PRODUTOS FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
	CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE VENDA (
	ID_VENDA INT NOT NULL,
	CPF_FUNCIONARIO VARCHAR(11) NOT NULL,
	CPF_CLIENTE VARCHAR(11) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	VALOR_TOTAL NUMERIC(10,2) NOT NULL,
	QUANTIDADE INT NOT NULL,
	FORMA_PAGAMENTO VARCHAR(20) NOT NULL,
	CONSTRAINT FK_FUNC_VENDA FOREIGN KEY (CPF_FUNCIONARIO) REFERENCES FUNCIONARIOS (CPF),
	CONSTRAINT FK_CLIENTE_VENDA FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES (CPF),
	CONSTRAINT FK_PRODUTO_VENDA FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO),
	CONSTRAINT PK_VENDA PRIMARY KEY (ID_VENDA)
);