CREATE TABLE BANCOS (
	COD_BANCO INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	AGENCIA INTEGER NOT NULL,
	NUMERO_BANCO INTEGER NOT NULL
);

ALTER TABLE BANCOS
ADD CONSTRAINT PK_BANCOS PRIMARY KEY (COD_BANCO);

CREATE TABLE DEPTOS (
	COD_DEPTO INTEGER NOT NULL,
	NOME VARCHAR(40)
);

ALTER TABLE DEPTOS
ADD CONSTRAINT PK_DEPTOS PRIMARY KEY (COD_DEPTO);

CREATE TABLE FUNCIONARIOS (
	COD_FUNC INTEGER NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	COD_DEPTO INTEGER NOT NULL,
	SALARIO NUMERIC (10,2) NOT NULL,
	DT_ADMISSAO DATE,
	DT_NASCTO DATE,
	COD_BANCO INTEGER NOT NULL
);

ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY (COD_FUNC),
ADD CONSTRAINT FK_DEPTOS_FUNCIONARIOS FOREIGN KEY (COD_DEPTO) REFERENCES DEPTOS (COD_DEPTO),
ADD CONSTRAINT FK_BANCOS_FUNCIONARIOS FOREIGN KEY (COD_BANCO) REFERENCES BANCOS (COD_BANCO);

SELECT * FROM BANCOS;

ALTER TABLE BANCOS
ALTER COLUMN AGENCIA
TYPE VARCHAR(10),
ALTER COLUMN NUMERO_BANCO
TYPE VARCHAR(10);

INSERT INTO BANCOS
VALUES
(1, 'Banco do Brasil', '0407-3', '6620-6'),
(2, 'Bradesco', '500-4', '1246-88');

UPDATE BANCOS SET NOME = 'NUBANK'
WHERE COD_BANCO = 1;